-Areas, perimetro de triangulos equilatero

-Recibe una lista de 16 elementos, la transforme en una matriz de tamaño 4x4

-Función que calcule el determinante (np.linalg.det(A))

In [19]:
import numpy as np
# Creamos la clase madre que se llama Formulas
class Formulas:
    def area(self):
        pass

    def perimetro(self):
        pass
# Creamos la clase heredada de Formulas para calcular el area y perímetro
class TrianguloEquilatero(Formulas):
    def __init__(self, lado):
        self.lado = lado

    def area(self):
        return (np.sqrt(3) / 4) * self.lado**2

    def perimetro(self):
        return 3 * self.lado

# Ingresamos la longitud del lado del triángulo equilátero
longitud_lado = float(input("Ingresa la longitud del lado del triángulo equilátero: "))

# Creamos una instancia de la clase TrianguloEquilatero
triangulo = TrianguloEquilatero(longitud_lado)

# Calculamos el area y el perimetro utilizando la clase
area = triangulo.area()
perimetro = triangulo.perimetro()

# Resultados dados del codigo
print(f"Área del triángulo equilátero: {area}")
print(f"Perímetro del triángulo equilátero: {perimetro}")



Ingresa la longitud del lado del triángulo equilátero: 5
Área del triángulo equilátero: 10.825317547305483
Perímetro del triángulo equilátero: 15.0


In [18]:
import numpy as np
# Creamos la clase madre del codigo
class TransformadorMatriz:
    def lista_a_matriz(self, lista):
        matriz = np.array(lista).reshape(4, 4)
        return matriz

# Creamos la clase heredada de TransformadorMatriz para calcular el determinante
class CalculadorDeterminante(TransformadorMatriz):
    def calcular_determinante(self, matriz):
        return np.linalg.det(matriz)

# Ingresamos la lista de 16 elementos
lista_16_elementos = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

# Creamos una instancia de la clase que se llamara TransformadorMatriz
transformador = TransformadorMatriz()

# Transformamos la lista en una matriz 4x4 utilizando la clase
matriz_resultante = transformador.lista_a_matriz(lista_16_elementos)

# Mostramos la matriz resultante
print("Matriz resultante:")
print(matriz_resultante)

# Creamos una instancia de la clase heredada para calcular el determinante
calculador_determinante = CalculadorDeterminante()

# Calculamos el determinante utilizando la clase heredada
determinante = calculador_determinante.calcular_determinante(matriz_resultante)

# Resultado
print("Determinante de la matriz:")
print(determinante)


Matriz resultante:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Determinante de la matriz:
0.0
